name:                renkon
version:             0.1.0.0
homepage:            https://github.com/kayhide/renkon
license:             BSD3
author:              Hideaki KAWAI
maintainer:          kayhide@gmail.com
copyright:           2017 kayhide
category:            Development
#synopsis:
description: |
  Text based template manager

extra-source-files:
  - README.md

dependencies:
  - aeson
  - ansi-terminal
  - base
  - classy-prelude
  - directory
  - exceptions
  - file-embed
  - filemanip
  - filepath
  - foldl
  - formatting
  - inflections
  - lens
  - megaparsec
  - mtl
  - optparse-applicative
  - path
  - path-io
  - process
  - stache
  - text
  - transformers

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs:      src

executables:
  renkon:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - renkon

tests:
  dev:
    source-dirs: test/dev
    main: Main.hs
    dependencies:
      - renkon
