name:                configurable
version:             0.1.0.0
homepage:            https://github.com/kayhide/configurable
license:             BSD3
author:              Hideaki KAWAI
maintainer:          kayhide@gmail.com
copyright:           kayhide
category:            Development
#synopsis:
description: |
  Pluggable configuration support

extra-source-files:
  - README.md

dependencies:
  - async
  - base
  - bytestring
  - classy-prelude
  - containers
  - deepseq
  - directory
  - exceptions
  - extensible
  - filepath
  - lens
  - mtl
  - primitive
  - stm
  - text
  - time
  - transformers
  - typed-process
  - unliftio
  - unliftio-core
  - unordered-containers
  - vector

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src
